### ISSUE TITLE
nil pointer dereference when a depends-on name is not valid

### ISSUE THREAD

**Issue by alexchao26** [alexchao26/oneterminal#3]
Simple config to reproduce error:

```yml
name: ticker-example
commands:
- name: ticker-UNO
  command: go run main.go
  ready-regexp: "tick [6-9]"
  directory: $HOME/go/src/github.com/alexchao26/oneterminal/examples/ticker
- name: ticker-two
  command: SECONDS=3 go run main.go
  directory: $HOME/go/src/github.com/alexchao26/oneterminal/examples/ticker
  depends-on:
    - ticker-UNO
    - bad-depends-on-name
```

Outputs: 
```sh
$ oneterminal ticker-example 
ticker-UNO | tick 0
ticker-UNO | tick 1
ticker-UNO | tick 2
ticker-UNO | tick 3
ticker-UNO | tick 4
ticker-UNO | tick 5
ticker-UNO | tick 6
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x29 pc=0x11c162d]

goroutine 36 [running]:
github.com/alexchao26/oneterminal/internal/monitor.(*MonitoredCmd).IsReady(...)
	/Users/chao/go/src/github.com/alexchao26/oneterminal/internal/monitor/command.go:114
github.com/alexchao26/oneterminal/internal/monitor.checkDependencies(0xc000108280, 0xc000098000, 0x0)
	/Users/chao/go/src/github.com/alexchao26/oneterminal/internal/monitor/orchestrator.go:98 +0x8d
github.com/alexchao26/oneterminal/internal/monitor.(*Orchestrator).RunCommands.func2(0xc000150c80, 0xc000098000, 0xc000108280)
	/Users/chao/go/src/github.com/alexchao26/oneterminal/internal/monitor/orchestrator.go:74 +0xa8
created by github.com/alexchao26/oneterminal/internal/monitor.(*Orchestrator).RunCommands
	/Users/chao/go/src/github.com/alexchao26/oneterminal/internal/monitor/orchestrator.go:60 +0x21f
```

Should give a meaningful error message that there is no command with ${unspecified name}
